print('hi, visitor!\ndid you like my github?')
print('hi')
print('ManU sucks now a days. f you, ily!')
print('1')
print('hola')
print('jesper')
print(1)
print(6)
print(10)
print(100)
print('ay yo')
print('Joseph')
print('f')
print('789')
print('5665')
